<?xml version="1.0" encoding="utf-8"?><Database Name="Empresa" Class="DepartamentosFuncionariosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Empresa.mdf;Integrated Security=True" SettingsObjectName="LinqToSql_Console.Properties.Settings" SettingsPropertyName="EmpresaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Departamentos" Member="Departamentos">
    <Type Name="Departamentos">
      <Column Name="Sigla" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Departamento" Member="Departamento1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Departamento_Funcionario" Member="Funcionarios" ThisKey="Sigla" OtherKey="Departamento" Type="Funcionarios" />
    </Type>
  </Table>
  <Table Name="dbo.Funcionarios" Member="Funcionarios">
    <Type Name="Funcionarios">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Departamento" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Departamento_Funcionario" Member="Departamentos" ThisKey="Departamento" OtherKey="Sigla" Type="Departamentos" IsForeignKey="true" />
    </Type>
  </Table>
</Database>